platform :ios, '8.0'

target 'RNWKWebViewBridge' do
  use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge',
    'RCTText',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/'
end
